### ISSUE TITLE
Find different approach for tagging patches

### ISSUE THREAD

**Issue by razbakov** [firegento/magento-ce#5]
Using tags which could be potentially released by magento is not good approach

**Comment by SchumacherFM** [comment]
I know :-(

any other idea?

**Comment by razbakov** [comment]
maybe 1.9.0.1-patch1 ?

**Comment by SchumacherFM** [comment]
The last time I have had collision with a tag which got released by Magento ... I've simply deleted my tag and recreated it with the new released version. Then checked if the patches have been applied. If not I've created the next version.

Silent replacement ... good or bad?

**Comment by razbakov** [comment]
AFAIK it is bad to delete tags. 
maybe use `v1.9.0.1` for official and `1.9.0.2` for unofficial?
or some prefix?

**Comment by razbakov** [comment]
then everyone who is using `~v.1.9.0` will get only official packages and `~1.9.0` will get latest.

**Comment by SchumacherFM** [comment]
that is an awesome idea! if you want you can delete the tags and recreate them.

make sure to checkout the correct commit and create a signed tag.

otherwise I can do it tomorrow.

**Comment by razbakov** [comment]
what does it mean "signed tag"?

**Comment by SchumacherFM** [comment]
http://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

If you sign it remove my last comment in the README.md file

**Comment by Flyingmana** [comment]
differentiate bei v / not v does not work with composer, as it trys for both to convert them to a semver version.

silent replace will cause problems for people already using it. It can happen, that update does not work for them, or install, because the signature of the download differs from the one, stored in composer.lock
And such difference usually leads to people believe of an security problem. And thats good and intended that they do believe this. If the most official source for this does recommend to ignore this warning, people will be more careless and ignore it, when a real security breach happens. 

use the +patch1 annotation. Important, use `+` not `-` as the second one notes a pre release. But there is some testing needed, how it affects version resolvement during updates.

**Comment by SchumacherFM** [comment]
Fixed like Daniel suggested.
